matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode10.1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
    packages:
      - clang-7
      - clang++-7

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
before_install:
  - export CC=clang-7
  - export CXX=clang++-7
install:
  - pip install
script:
  - python -c 'from kcollections import Kset, Kdict'
