dist: trusty
matrix:
  include:
    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - clang++-7
      script:
        - export CC=clang-7
        - export CXX=clang++-7
        - mkdir build && cd build && cmake .. && make -j 4

    - language: python
      python:
        - "2.7"
        - "3.6"
        - "3.7"
      install:
        pip install . && pip3 install .
      script:
        - python2 -c 'from kcollections import Kset, Kdict'
        - python3 -c 'from kcollections import Kset, Kdict'
