matrix:
  include:
    - os: linux
      sudo: required
      language: python
      python: "3.7"
      env: TOXENV=py37
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
          packages:
            - cmake
            - clang-7
            - clang++-7

    - os: linux
      python: 2.7
      env: TOXENV=py27
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - cmake
            - clang-7
            - clang++-7

    - os: osx
      osx_image: xcode10.1
      language: generic
      env: TOXENV=py37

    - os: osx
      osx_image: xcode10.1
      language: generic
      env: TOXENV=py27



before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ] && [ $TOXENV == "py27" ]; then brew update && brew install python@2; fi
  - if [ $TRAVIS_OS_NAME == "osx" ] && [ $TOXENV == "py37" ]; then brew update && brew install python; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export CC=clang-7; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX=clang++-7; fi
install:
  - if [ $TOXENV == "py27" ]; then sudo pip2 install .; else sudo pip3 install .; fi
script:
  - cd
  - if [ $TOXENV == "py27" ];
    then python2 -c 'from kcollections import Kset, Kdict';
    else python3 -c 'from kcollections import Kset, Kdict';
    fi
