matrix:
  include:
    - os: linux
      sudo: yes
      python: 3.7
      env: TOXENV=py37
      dist: xenial

    - os: linux
      python: 2.7
      env: TOXENV=py27
      dist: trusty

    - os: osx
      osx_image: xcode10.1
      language: generic
      env: TOXENV=py37

    - os: osx
      osx_image: xcode10.1
      language: generic
      env: TOXENV=py27

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
    packages:
      - cmake
      - clang-7
      - clang++-7

before_install:
  - if [ $TRAVIS_OS_NAME = osx && $TOXENV = py27 ]; then brew update && brew install python@2; fi
  - if [ $TRAVIS_OS_NAME = osx && $TOXENV = py37 ]; then brew update && brew install python; fi
  - export CC=clang-7
  - export CXX=clang++-7
install:
  - sudo pip install .
script:
  - cd
  - python -c 'from kcollections import Kset, Kdict'
