matrix:
  include:
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=linux BIT=64 PY=3
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
          PRE_CMD=linux32 PLAT=linux BIT=32 PY=3
   - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=linux BIT=64 PY=2
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
          PRE_CMD=linux32 PLAT=linux32 BIT=32 PY=2
  - os: osx
    osx_image: xcode10.1
    language: generic
    env: TOXENV=py37
  - os: osx
    osx_image: xcode10.1
    language: generic
    env: TOXENV=py27
before_install:
- if [ $TRAVIS_OS_NAME == "osx" ] && [ $TOXENV == "py27" ];
  then
    brew update;
    brew install python@2;
  fi
- if [ $TRAVIS_OS_NAME == "osx" ] && [ $TOXENV == "py37" ];
  then
    brew update;
    brew install python;
  fi

install:
  - if [ $PLAT == "linux" ];
    then
      docker pull $DOCKER_IMAGE;
      docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD generate_wheels.sh;
    fi

deploy:
  provider: pypi
  user: masakistan
  distributions: "sdist bdist_wheel"
  edge:
    branch: v1.8.45
  on:
    branch: master
  password:
    secure: I2Fq7TUUS7hXpFDEATnP2HHfw7oXRM6O+7vRqvUwTzIKTUHeceqG4Svzkp5kDd+NS2h9O5lu7cLVM8HQrv3CbH4/59ZdFG2kJE6oZ6vvfVHHA25whlqaqodM2qyWE4ZIayypn4EXB2pxpzqT5taGNTzgU/QRUIvSDrMcpZzel6xKhn9uiXXL72Qw2zh9Xk46eto07DS4nsUSTvUL6lMmQwwSoTTHL0cFEvxSG8/0SoUY7nkFj09plLAUd0HPCiBxG70fC63+qcYBZ5FC32Ez+zXVHVyI7+XYvRRnAEI+daDed+KzfFZwC3S4b9v5yYNZerT7Zrp9WHe9lm3URjR5QdmtjBb2WVqJX0PIkP7txLPsahFAhEBpD/+1+pJX7qmf55ipVrIExAgMJqAieerYm5qgXwnWeNy8qbdanMHUxbHKbJMA3e0PLMN8uvcGXXmh2sGcLTPpQ7erR/lM+gDtpKBRN/+DrpoF1RsnaxglzqZKfxxWkhKdNaPDzDZ3fd7nVJA+0Gd+eCACo2hEfFifx2yq84/EV6F+RJ+UyKULZhNozl5YdxK7UMs3joEcTTx41LSP65Onfphl+2budFe9R0t5NNJp+z32VdJ1lvUdt+k/KeMThhf+bYzeISOkc1qmyOkEOHMVGyOTYke9w5Nm+dydG6GWKW+K3M5vx2vYzH4=
