matrix:
  include:
    - os: linux
      language: cpp
      env: TOXENV=py37
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - clang++-7

    - os: linux
      language: cpp
      env: TOXENV=py27
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - clang++-7

    - os: osx
      osx_image: xcode10.1
      language: generic
      env: TOXENV=py37

    - os: osx
      osx_image: xcode10.1
      language: generic
      env: TOXENV=py27



before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ] && [ $TOXENV == "py27" ]; then
      brew update;
      brew install python@2;
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ] && [ $TOXENV == "py37" ]; then
      brew update;
      brew install python;
    fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get purge cmake;
      export CC=clang-7;
      export CXX=clang++-7;
      if [ $TOXENV == "py37" ]; then
        sudo apt-get install python3-pip python3-dev build-essential;
      else
        sudo apt-get install python-pip python-dev build-essential;
      fi
    fi

install:
  - if [ $TOXENV == "py27" ]; then
      echo "building for python 2 ...";
      python2 setup.py bdist_wheel;
      ls dist;
      pip2 install dist/*.whl;
    else
      echo "building for python 3 ...";
      python3 setup.py bdist_wheel;
      ls dist;
      pip3 install dist/*.whl;
    fi
script:
  - cd
  - if [ $TOXENV == "py27" ]; then
      echo "testing python 2";
      python2 -c 'from kcollections import Kset, Kdict';
    else
      echo "testing python 3";
      python3 -c 'from kcollections import Kset, Kdict';
    fi
